//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/zm_fox_v2.html
halflife.wad
cs_dust.wad
cs_assault.wad
models/player/gsg9/gsg9.mdl
models/player/guerilla/guerilla.mdl
cs_747.wad
torntextures.wad
maps/zm_fox_v2.bsp
