//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/zm_foda_v2.html
models/player/gsg9/gsg9.mdl
models/player/guerilla/guerilla.mdl
gfx/env/forestbk.tga
gfx/env/forestdn.tga
gfx/env/forestft.tga
gfx/env/forestlf.tga
gfx/env/forestrt.tga
gfx/env/forestup.tga
podbot/wptdefault/zm_foda_v2.pxp
maps/zm_foda_v2.bsp
