//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/zm_fox_v3.html
models/player/gsg9/gsg9.mdl
models/player/guerilla/guerilla.mdl
maps/zm_fox_v3.bsp
